### ISSUE TITLE
Migrate to ES6 export

### ISSUE THREAD

**Issue by shoonia** [mckamey/countdown.js#38]
The modern build tooling, browsers, and Nodejs support ES6 `import/export`. 

May you migrate to ES6 export instead of a hacky way to detect the environment

```js
export { countdown };
```

**Comment by patrickbenjamin1** [comment]
Yeah I'm having big issues trying to get rollup to bundle this module properly because it's using outdated imports/exports

What was your hacky solution?

**Comment by patrickbenjamin1** [comment]
I solved this by just copying countdown.js into my repo, removing 1346 to 1353, and adding `export default countdown`

I'd open a pull request but don't know much about the rest of the tooling and don't wanna break anything. If I get some time, I might fork the repo and make a more modern Typescript/ES Module version

**Comment by shoonia** [comment]
You can use the exports map.
example: https://github.com/preactjs/preact/blob/4aaecc18d33a9f3139ddd5f30f6d7c745076795f/package.json#L12-L18

And build a few entry point for each export variant
example with Rollup.js : https://github.com/shoonia/storeon-velo/blob/master/rollup.config.js#L22-L38

Playground: [https://rollupjs.org/repl/](https://rollupjs.org/repl/?version=2.58.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwY291bnRkb3duJTIwJTNEJTIwZnVuY3Rpb24lMjAoKSUyMCU3QiU1Q24lNUN0JTJGJTJGJTIwQm9keSUyMC4uLiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

**Comment by CalvinJamesHeath** [comment]
When I run the code after downloading the package.json file and the countdown.js file, I receive the following error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'hot')
    at $ReactRefreshModuleRuntime$ (countdown.js:1490:1)
    at ./src/components/Countdown/countdown.js (countdown.js:1490:1)
    at options.factory (react refresh:6:1)`

I have already removed the lines from 1346 to 1353 and added export default countdown;
